### ISSUE TITLE
Extension gets activated for every xml file

### ISSUE THREAD

**Issue by younesZdDz** [younesZdDz/vscode-east#1]
The extension is getting activated for every XML files, we need to activate it for EAST files only.

![image](https://user-images.githubusercontent.com/32100131/103777649-80d51580-5031-11eb-9ecd-42de3d7f5a54.png)

**Comment by nasri-soufiane** [comment]
@younesZdDz  What do you think about activating it on *.east.xml files only and add condition to activate extension only when east.xsd and east.xslt are present in the folder. This way, we will have xml and EAST functionalities.

**Comment by younesZdDz** [comment]
@nasri-soufiane  Great suggestion, I will work on it !
